//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmWPF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class film1e4Entities : DbContext
    {
        public film1e4Entities()
            : base("name=film1e4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<acteur> acteur { get; set; }
        public virtual DbSet<appartenir> appartenir { get; set; }
        public virtual DbSet<cinema> cinema { get; set; }
        public virtual DbSet<film> film { get; set; }
        public virtual DbSet<genre> genre { get; set; }
        public virtual DbSet<jouer> jouer { get; set; }
        public virtual DbSet<parrution> parrution { get; set; }
        public virtual DbSet<personne> personne { get; set; }
        public virtual DbSet<realisateur> realisateur { get; set; }
        public virtual DbSet<salle> salle { get; set; }
        public virtual DbSet<spectateur> spectateur { get; set; }
    }
}
