//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class jouer
    {
        public int NumFilm { get; set; }
        public int NumActeur { get; set; }
        public string Role { get; set; }
    
        public virtual acteur acteur { get; set; }
        public virtual film film { get; set; }
    }
}
