//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class personne
    {
        public int Id { get; set; }
        public string Prenom { get; set; }
        public string Nom { get; set; }
        public System.DateTime DateNaissance { get; set; }
    
        public virtual acteur acteur { get; set; }
        public virtual realisateur realisateur { get; set; }
        public virtual spectateur spectateur { get; set; }
    }
}
