//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserver
    {
        public int NumFilm { get; set; }
        public int NumSpectateur { get; set; }
        public System.DateTime DateHeure { get; set; }
    
        public virtual film film { get; set; }
        public virtual spectateur spectateur { get; set; }
    }
}
